
services: 

  nats-server:
    image: nats:latest

  client-gateway:
    build: 
      context: ./client-gateway
      dockerfile: dockerfile.prod
    image: northamerica-south1-docker.pkg.dev/store-microservices-459102/image-registry/client-gateway
    ports:
      - 3001:3001
    environment:
      - PORT=3001
      - DATABASE_URL=file:./dev.db
      - NATS_SERVERS=nats://nats-server:4222
  auth-ms:
    build: 
      context: ./auth-microservice
      dockerfile: dockerfile.prod
    image: northamerica-south1-docker.pkg.dev/store-microservices-459102/image-registry/auth-microservice
    environment:
      - PORT=3004
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
  products-ms:
    build: 
      context: ./products-microservice
      dockerfile: dockerfile.prod
    image: northamerica-south1-docker.pkg.dev/store-microservices-459102/image-registry/products-microservice
    environment:
      - PORT=3001
      - DATABASE_URL=file:./dev.db
      - NATS_SERVERS=nats://nats-server:4222

  payments-ms:
    build: 
      context: ./payments-microservice
      dockerfile: dockerfile.prod
    image: northamerica-south1-docker.pkg.dev/store-microservices-459102/image-registry/payments-microservice
    environment:
      - PORT=3003
      - STRIPE_SECRET=${STRIPE_SECRET}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - SUCCESS_URL=${SUCCESS_URL}
      - CANCEL_URL=${CANCEL_URL}      
      - NATS_SERVERS=nats://nats-server:4222

  orders-ms:
    build: 
      context: ./orders-microservice
      dockerfile: dockerfile.prod
      args:
        - ORDERS_DATABASE_URL=${ORDERS_DATABASE_URL}
    image: northamerica-south1-docker.pkg.dev/store-microservices-459102/image-registry/orders-microservice
    environment:
      - PORT=3002
      - DATABASE_URL=${ORDERS_DATABASE_URL}
      - NATS_SERVERS=nats://nats-server:4222