
services: 

  nats-server:
    image: nats:latest
    ports:
      - 8222:8222
  client-gateway:
    build: ./client-gateway
    ports:
      - 3000:3000
    restart: always
    volumes:
      - ./client-gateway/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats-server:4222
  products-ms:
    build: ./products-microservice
    restart: always
    volumes:
      - ./products-microservice/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3001
      - DATABASE_URL=file:./dev.db
      - NATS_SERVERS=nats://nats-server:4222
  
  orders-db:
    container_name: orders_database
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./orders-microservice/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  orders-ms:
    build: ./orders-microservice
    depends_on:
      - orders-db
    restart: always
    volumes:
      - ./orders-microservice/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3002
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${DB_PASSWORD}@orders-db:5432/ordersdb
      - NATS_SERVERS=nats://nats-server:4222
  auth-ms:
    build: ./auth-microservice
    restart: always
    volumes:
      - ./auth-microservice/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3004
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
  payments-ms:
    container_name: payments-ms
    build: ./payments-microservice
    restart: always
    volumes:
      - ./payments-microservice/src:/usr/src/app/src
    command: yarn start:dev
    ports:
      - 3003:3003
    environment:
      - PORT=3003
      - STRIPE_SECRET=${STRIPE_SECRET}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - SUCCESS_URL=${SUCCESS_URL}
      - CANCEL_URL=${CANCEL_URL}      
      - NATS_SERVERS=nats://nats-server:4222
      
      